import React from "react";
import { Col, Row } from "antd";
import CustomCard from "../../Components/CustomCard";

const Uniquefeatures = () => {
  return (
    <section className="Uniquefeatures section">
      <div className="container">
        <center
          style={{
            maxWidth: "850px",
            margin: "0 auto",
            width: "100%",
            marginBottom: "5%",
          }}
        >
          <h2>Unique features of the app</h2>
          <p>
            The Joud Taxi app will provide a unique and safe ride-hailing
            experience for women and children, with features designed
            specifically to meet their needs and preferences.
          </p>
        </center>
        <Row gutter={[30, 30]}>
          <Col xs={24} sm={24} md={12} lg={8} xl={8}>
            <CustomCard
              image="images/values-1.png"
              title="Emergency button"
              description="The app will include an emergency button that passengers can press in case of an emergency, immediately alerting Joud Taxi's emergency response team and providing their exact location."
            />
          </Col>
          <Col xs={24} sm={24} md={12} lg={8} xl={8}>
            <CustomCard
              image="images/values-2.png"
              title="Women's safety features"
              description="The app will provide additional safety features for women, such as the ability to share their ride details with a friend or family member and a panic button that will alert the police in case of danger."
            />
          </Col>
          <Col xs={24} sm={24} md={12} lg={8} xl={8}>
            <CustomCard
              image="images/values-3.png"
              title="Social responsibility"
              description="The Joud Taxi app will also emphasize social responsibility, by partnering with local charities and organizations that support women and children's causes. A portion of the profits generated by the app could be donated to these causes, helping to make a positive impact in the community."
            />
          </Col>
        </Row>
      </div>
    </section>
  );
};

export default Uniquefeatures;
